### ISSUE TITLE
Normalize description of existing projects & project ideas proposed for this season

### ISSUE THREAD

**Issue by Patechoc** [DataForGood-Norway/season-1#3]
already 5 projects:

* OrcaTag
* Vertical Farming
* Ratifications of UN Treaties
* Teaching sessions by GirlsCanDoIT
* Teaching sessions by Ali

**Comment by Patechoc** [comment]
can get inspired by the presentation of United Nations Unites Challenges: https://uniteideas.spigit.com/sustainablecities/Page/ViewIdeas

**Comment by Elowane** [comment]
Proposal for a short ID-card to be written for each project we want to propose:
- Project title: 
- Context: (issue to be solved)
- Task description: 
- Final goal: (that should be reached at the end of the 3 months)
- Needs: (skills needed in the team)
- Data set: (if relevant for some projects?)
- Contact: (D4G person presenting the project)

For example:
- **Project title**: Familiblad
- **Context**: It is very easy to stay connected to friends and family, even from far away, thanks to Facebook, WhatsApp or by email. However people not connected to the internet (for example the elderly) are more isolated than before and get less news from their family.
- **Task description**: Build a web-app and mobile app so that several family members can upload pictures and news in a private account, which are automatically and periodically transformed in a pdf newsletter and sent to the family members. One of them can then print it and send it to the family member which does not have internet.
- **Final goal**: working website + mobile app
- **Needs**: Developer Back-end (database) + Front-End Mobile app + Front-End Web app
- **Data set**: -
- **Contact**: Nolwenn
